### PR TITLE
fs_watcher：修复冲突，对write系统调用，添加了提取路径参数信息

### PR DESCRIPTION
**Pull request by sf1999817**
# Pull Request Template

## Description/描述

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
此 pr 解决了什么问题

Fixes # (issue)

## Type of change /PR 类型

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?/ 测试方式

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Checklist/检查列表

- [ ] My code follows the style guidelines of this project /代码规范检查
- [ ] I have performed a self-review of my own code / 自己已经检查代码
- [ ] I have commented my code, particularly in hard-to-understand areas / 有代码注释，尤其是关键代码
- [ ] I have made corresponding changes to the documentation /变更内容同步到了文档中
- [ ] My changes generate no new warnings / 变更没有新产生告警
- [ ] I have added tests that prove my fix is effective or that my feature works /对修改代码添加了测试用例
- [ ] New and existing unit tests pass locally with my changes / 对单元测试也同步更新了

### CODE REVIEW

**Comment by helight** [comment]
这里还是有冲突呀？再看看

image

**Comment by sf1999817** [comment]
> 这里还是有冲突呀？再看看
> 
> image

师兄，我刚刚又修了，现在好了吗？

**Comment by helight** [comment]
> > 这里还是有冲突呀？再看看
> > image
> 
> 师兄，我刚刚又修了，现在好了吗？

可以了，这里在提交内容中增加一下你运行的截图，补充一下readme

**Comment by sf1999817** [comment]
> > > 这里还是有冲突呀？再看看
> > > image
> > 
> > 
> > 师兄，我刚刚又修了，现在好了吗？
> 
> 可以了，这里在提交内容中增加一下你运行的截图，补充一下readme

运行截图

师兄，那么reademe，我再补充一下那个read的代码，然后明天一起提交。

**Comment by helight** [comment]
@13186379707 review一下

**Review by 13186379707 — DISMISSED** [review]

**Comment by sf1999817** [comment]
jiovodshvosnvnosnvkslbnsl
重新优化了read的提取参数，如图所示，打印了文件名称、还有读取的文件大小字节数
如果我们使用cat命令，读取这个111.txt文件里面的数据信息，就会触发vfs_read内核函数，就会打印它的文件名称以及它的字节数

**Review by chenamy2017 — APPROVED** [review]

**Review by helight — APPROVED** [review]

**Pull request merged**
